// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UniformSystem.Data;

#nullable disable

namespace UniformSystem.Migrations
{
    [DbContext(typeof(AppDatabaseContext))]
    [Migration("20260906150718_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UniformSystem.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("UniformSystem.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("UniformId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UniformId");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("UniformSystem.Models.InventoryLogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LogDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UniformId")
                        .HasColumnType("integer");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LogDate");

                    b.HasIndex("UniformId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("InventoryLogs");
                });

            modelBuilder.Entity("UniformSystem.Models.Uniform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<char>("Sex")
                        .HasColumnType("character(1)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UniformCategoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("Sex");

                    b.HasIndex("UniformCategoryId");

                    b.ToTable("Uniform");
                });

            modelBuilder.Entity("UniformSystem.Models.UniformCategory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("UniformCategory");
                });

            modelBuilder.Entity("UniformSystem.Models.UniformDelivered", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DeliveredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DeliveredById")
                        .HasColumnType("integer");

                    b.Property<int>("ToEmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("UniformId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeliveredAt");

                    b.HasIndex("DeliveredById");

                    b.HasIndex("ToEmployeeId");

                    b.HasIndex("UniformId");

                    b.ToTable("UniformDelivered");
                });

            modelBuilder.Entity("UniformSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("UniformSystem.Models.Inventory", b =>
                {
                    b.HasOne("UniformSystem.Models.Uniform", "Uniform")
                        .WithMany("Inventories")
                        .HasForeignKey("UniformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniformSystem.Models.User", "UpdatedBy")
                        .WithMany("Inventories")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uniform");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("UniformSystem.Models.InventoryLogs", b =>
                {
                    b.HasOne("UniformSystem.Models.Uniform", "Uniform")
                        .WithMany("InventoryLogs")
                        .HasForeignKey("UniformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniformSystem.Models.User", "UpdatedBy")
                        .WithMany("InventoryLogs")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uniform");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("UniformSystem.Models.Uniform", b =>
                {
                    b.HasOne("UniformSystem.Models.UniformCategory", "UniformCategory")
                        .WithMany()
                        .HasForeignKey("UniformCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UniformCategory");
                });

            modelBuilder.Entity("UniformSystem.Models.UniformDelivered", b =>
                {
                    b.HasOne("UniformSystem.Models.User", "DeliveredBy")
                        .WithMany("UniformDelivered")
                        .HasForeignKey("DeliveredById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniformSystem.Models.Employee", "ToEmployee")
                        .WithMany("UniformDelivered")
                        .HasForeignKey("ToEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniformSystem.Models.Uniform", "Uniform")
                        .WithMany("UniformDelivered")
                        .HasForeignKey("UniformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveredBy");

                    b.Navigation("ToEmployee");

                    b.Navigation("Uniform");
                });

            modelBuilder.Entity("UniformSystem.Models.Employee", b =>
                {
                    b.Navigation("UniformDelivered");
                });

            modelBuilder.Entity("UniformSystem.Models.Uniform", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("InventoryLogs");

                    b.Navigation("UniformDelivered");
                });

            modelBuilder.Entity("UniformSystem.Models.User", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("InventoryLogs");

                    b.Navigation("UniformDelivered");
                });
#pragma warning restore 612, 618
        }
    }
}
