// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UniformSystem.Data;

#nullable disable

namespace UniformSystem.Migrations
{
    [DbContext(typeof(AppDatabaseContext))]
    partial class AppDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UniformSystem.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tb_employees");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_tb_employees_email");

                    b.ToTable("tb_employees", (string)null);
                });

            modelBuilder.Entity("UniformSystem.Entities.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<int>("UniformId")
                        .HasColumnType("integer")
                        .HasColumnName("uniform_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_tb_inventory");

                    b.HasIndex("UniformId")
                        .HasDatabaseName("ix_tb_inventory_uniform_id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_tb_inventory_updated_at");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_tb_inventory_updated_by_id");

                    b.ToTable("tb_inventory", (string)null);
                });

            modelBuilder.Entity("UniformSystem.Entities.InventoryLogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<DateTime>("LogDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("log_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UniformId")
                        .HasColumnType("integer")
                        .HasColumnName("uniform_id");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_tb_inventory_logs");

                    b.HasIndex("LogDate")
                        .HasDatabaseName("ix_tb_inventory_logs_log_date");

                    b.HasIndex("UniformId")
                        .HasDatabaseName("ix_tb_inventory_logs_uniform_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_tb_inventory_logs_updated_by_id");

                    b.ToTable("tb_inventory_logs", (string)null);
                });

            modelBuilder.Entity("UniformSystem.Entities.Uniform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.Property<char>("Sex")
                        .HasColumnType("character(1)")
                        .HasColumnName("sex");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("size");

                    b.Property<int>("UniformCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("uniform_category_id");

                    b.HasKey("Id")
                        .HasName("pk_tb_uniform");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_tb_uniform_name");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ix_tb_uniform_reference");

                    b.HasIndex("Sex")
                        .HasDatabaseName("ix_tb_uniform_sex");

                    b.HasIndex("UniformCategoryId")
                        .HasDatabaseName("ix_tb_uniform_uniform_category_id");

                    b.ToTable("tb_uniform", (string)null);
                });

            modelBuilder.Entity("UniformSystem.Entities.UniformCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tb_uniform_category");

                    b.ToTable("tb_uniform_category", (string)null);
                });

            modelBuilder.Entity("UniformSystem.Entities.UniformDelivered", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<DateTime>("DeliveredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DeliveredById")
                        .HasColumnType("integer")
                        .HasColumnName("delivered_by_id");

                    b.Property<int>("ToEmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("to_employee_id");

                    b.Property<int>("UniformId")
                        .HasColumnType("integer")
                        .HasColumnName("uniform_id");

                    b.HasKey("Id")
                        .HasName("pk_tb_uniforms_delivered");

                    b.HasIndex("DeliveredAt")
                        .HasDatabaseName("ix_tb_uniforms_delivered_delivered_at");

                    b.HasIndex("DeliveredById")
                        .HasDatabaseName("ix_tb_uniforms_delivered_delivered_by_id");

                    b.HasIndex("ToEmployeeId")
                        .HasDatabaseName("ix_tb_uniforms_delivered_to_employee_id");

                    b.HasIndex("UniformId")
                        .HasDatabaseName("ix_tb_uniforms_delivered_uniform_id");

                    b.ToTable("tb_uniforms_delivered", (string)null);
                });

            modelBuilder.Entity("UniformSystem.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_tb_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_tb_user_email");

                    b.ToTable("tb_user", (string)null);
                });

            modelBuilder.Entity("UniformSystem.Entities.Inventory", b =>
                {
                    b.HasOne("UniformSystem.Entities.Uniform", "Uniform")
                        .WithMany("Inventories")
                        .HasForeignKey("UniformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tb_inventory_uniforms_uniform_id");

                    b.HasOne("UniformSystem.Entities.User", "UpdatedBy")
                        .WithMany("Inventories")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tb_inventory_users_updated_by_id");

                    b.Navigation("Uniform");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("UniformSystem.Entities.InventoryLogs", b =>
                {
                    b.HasOne("UniformSystem.Entities.Uniform", "Uniform")
                        .WithMany("InventoryLogs")
                        .HasForeignKey("UniformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tb_inventory_logs_uniforms_uniform_id");

                    b.HasOne("UniformSystem.Entities.User", "UpdatedBy")
                        .WithMany("InventoryLogs")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tb_inventory_logs_users_updated_by_id");

                    b.Navigation("Uniform");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("UniformSystem.Entities.Uniform", b =>
                {
                    b.HasOne("UniformSystem.Entities.UniformCategory", "UniformCategory")
                        .WithMany()
                        .HasForeignKey("UniformCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tb_uniform_tb_uniform_category_uniform_category_id");

                    b.Navigation("UniformCategory");
                });

            modelBuilder.Entity("UniformSystem.Entities.UniformDelivered", b =>
                {
                    b.HasOne("UniformSystem.Entities.User", "DeliveredBy")
                        .WithMany("UniformDelivered")
                        .HasForeignKey("DeliveredById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tb_uniforms_delivered_users_delivered_by_id");

                    b.HasOne("UniformSystem.Entities.Employee", "ToEmployee")
                        .WithMany("UniformDelivered")
                        .HasForeignKey("ToEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tb_uniforms_delivered_tb_employees_to_employee_id");

                    b.HasOne("UniformSystem.Entities.Uniform", "Uniform")
                        .WithMany("UniformDelivered")
                        .HasForeignKey("UniformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tb_uniforms_delivered_tb_uniform_uniform_id");

                    b.Navigation("DeliveredBy");

                    b.Navigation("ToEmployee");

                    b.Navigation("Uniform");
                });

            modelBuilder.Entity("UniformSystem.Entities.Employee", b =>
                {
                    b.Navigation("UniformDelivered");
                });

            modelBuilder.Entity("UniformSystem.Entities.Uniform", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("InventoryLogs");

                    b.Navigation("UniformDelivered");
                });

            modelBuilder.Entity("UniformSystem.Entities.User", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("InventoryLogs");

                    b.Navigation("UniformDelivered");
                });
#pragma warning restore 612, 618
        }
    }
}
